# this is redis config file
[list]
    [list.default]
        proxy_list = ["xxx.190.58.175:6380"]
        password = "licslan"
        max_active = 100
        max_idle = 100
        down_grade = false
